<?php

/**
 * @file
 * Provides field value fallback provider test assets.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\Tests\view_mode_switch\Kernel\Entity\EntityViewModeDeleteFormHelperTest::testAlterExceptionsForWrongEntityType()
 */
function view_mode_switch_test_form_entity_test_entity_test_delete_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $form_object->getEntity();

  // Is executed in view mode switch form alter test context?
  if (!empty($entity->view_mode_switch_form_alter_test)) {
    // Try to apply form alter from view mode helper -> has to result in an
    // exception.
    /** @var \Drupal\view_mode_switch\Entity\EntityViewModeDeleteFormHelperInterface $entity_view_mode_delete_form_helper */
    $entity_view_mode_delete_form_helper = \Drupal::service('view_mode_switch.entity_view_mode_delete_form_helper');
    $entity_view_mode_delete_form_helper->alter($form, $form_state);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\Tests\view_mode_switch\Kernel\Entity\EntityViewModeDeleteFormHelperTest::testAlterExceptionsForWrongOperation()
 */
function view_mode_switch_test_form_entity_view_mode_edit_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  /** @var \Drupal\Core\Entity\EntityFormInterface $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\Core\Entity\EntityViewModeInterface $entity */
  $entity = $form_object->getEntity();
  // Is executed in view mode switch form alter test context?
  if (!empty($entity->view_mode_switch_form_alter_test)) {
    // Try to apply form alter from view mode helper -> has to result in an
    // exception.
    /** @var \Drupal\view_mode_switch\Entity\EntityViewModeDeleteFormHelperInterface $entity_view_mode_delete_form_helper */
    $entity_view_mode_delete_form_helper = \Drupal::service('view_mode_switch.entity_view_mode_delete_form_helper');
    $entity_view_mode_delete_form_helper->alter($form, $form_state);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\Tests\view_mode_switch\Kernel\Entity\EntityViewModeDeleteFormHelperTest::testAlterExceptionsForNonEntityForm()
 */
function view_mode_switch_test_form_system_rss_feeds_settings_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  $build_info = $form_state->getBuildInfo();

  // Is executed in view mode switch form alter test context?
  if (!empty($build_info['args'][0]['view_mode_switch_form_alter_test'])) {
    // Try to apply form alter from view mode helper -> has to result in an
    // exception.
    /** @var \Drupal\view_mode_switch\Entity\EntityViewModeDeleteFormHelperInterface $entity_view_mode_delete_form_helper */
    $entity_view_mode_delete_form_helper = \Drupal::service('view_mode_switch.entity_view_mode_delete_form_helper');
    $entity_view_mode_delete_form_helper->alter($form, $form_state);
  }
}
